function [hash] = string2hash(str, type)
    
    % convert a string in a hash value using two possible hash types
    % str - string to be converted
    % type - hash type ('djb2' or 'sdbm') Standart = 'djb2'
    % hash - hash value generated by the string

    str = double(str);

    % defines 'djb2' as standart if any type is specified
    if (nargin < 2), type = 'djb2'; end
    
    % determinates what happens in each case
    switch(type)
        case 'djb2'

            hash = 5381*ones(size(str,1),1); 

            for i=1:size(str,2)
                hash = mod(hash * 33 + str(:,i), 2^32-1); 
            end

        case 'sdbm'

            hash = zeros(size(str,1),1);

            for i=1:size(str,2)
                hash = mod(hash * 65599 + str(:,i), 2^32-1);
            end
            
        otherwise
            error('string_hash:inputs','unknown type');
    end
end